CREATE TABLE comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  url_id INT NOT NULL,
  user_id INT NOT NULL,
  comment TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (url_id) REFERENCES urls(id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);